spring:
  h2.console:
    enabled: true
    path: "/console"
  datasource:
    url: jdbc:h2:file:/Users/dibangshuwaddar/Downloads/todo-notepad/todo-db
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true






