spring:
  h2.console:
    enabled: true
    path: "/console"
  datasource:
    url: "jdbc:h2:file:/Users/kamilfuks/Downloads/todo-notepad/todo-db"
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true






